### ISSUE TITLE
Build bucket

### ISSUE THREAD

**Issue by AlexeyTyurenkov** [ITAAcademy/ITAInformator#22]
Please, inform me about needs for our application to be able to use separatly from QtCreator

**Comment by andy-vin** [comment]
For final version I want to use WiX to create installation package.
If you want to run application *.exe on computer where not installed Qt, you should use some libraries and file qt.conf  from Qt. If you want I make folder with need's files and share it for all

**Comment by Lenka2023** [comment]
Add Installer
